# Generated by Django 4.2 on 2024-01-30 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'bookings'},
        ),
    ]
