# Generated by Django 4.2 on 2024-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_reservation_booking_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title', 'inventory', 'price'], 'verbose_name_plural': 'Menu'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
