# Generated by Django 4.2 on 2024-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menu_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['reservation_date', 'reservation_slot'], 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='reservation_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='reservation_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='party_size',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
