# Generated by Django 4.2 on 2024-02-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_booking_email_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name', 'inventory', 'price'], 'verbose_name_plural': 'Menu'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='name',
        ),
    ]
